//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class field
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public float longitude { get; set; }
        public float latitude { get; set; }
        public int sport { get; set; }
        public bool enabled { get; set; }
    }
}
