//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameswonview
    {
        public int League { get; set; }
        public int season { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public long GamesWon { get; set; }
    }
}
