//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public int Id { get; set; }
        public int week { get; set; }
        public System.DateTime date { get; set; }
        public int team1 { get; set; }
        public sbyte scoreTeam1 { get; set; }
        public int team2 { get; set; }
        public sbyte scoreTeam2 { get; set; }
        public int field { get; set; }
        public string details { get; set; }
        public bool finished { get; set; }
        public int winner { get; set; }
        public bool draw { get; set; }
        public bool forfeit { get; set; }
        public bool enabled { get; set; }
    }
}
