//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public string TeamsId { get; set; }
        public System.DateTime Date { get; set; }
        public int type { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public bool Enabled { get; set; }
    }
}
