//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoretableview
    {
        public int season { get; set; }
        public int team { get; set; }
        public Nullable<long> GamesPlayed { get; set; }
        public Nullable<long> GamesWon { get; set; }
        public Nullable<long> GamesDrawn { get; set; }
        public Nullable<long> GamesLost { get; set; }
        public Nullable<decimal> ScoreFavor { get; set; }
        public Nullable<decimal> ScoreAgainst { get; set; }
        public Nullable<decimal> ScoreDifference { get; set; }
    }
}
