//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versusBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escorcenterdbEntities : DbContext
    {
        public escorcenterdbEntities()
            : base("name=escorcenterdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<field> fields { get; set; }
        public DbSet<league> leagues { get; set; }
        public DbSet<match> matches { get; set; }
        public DbSet<notification> notifications { get; set; }
        public DbSet<notificationtype> notificationtypes { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<season> seasons { get; set; }
        public DbSet<team> teams { get; set; }
        public DbSet<week> weeks { get; set; }
        public DbSet<subscribedteam> subscribedteams { get; set; }
        public DbSet<gamesdrawnview> gamesdrawnviews { get; set; }
        public DbSet<gamesplayedview> gamesplayedviews { get; set; }
        public DbSet<gameswonview> gameswonviews { get; set; }
        public DbSet<league_season_weekview> league_season_weekview { get; set; }
        public DbSet<scoreagainstview> scoreagainstviews { get; set; }
        public DbSet<scorefavorview> scorefavorviews { get; set; }
        public DbSet<scoretableview> scoretableviews { get; set; }
    }
}
