//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LeagueDTO.proto
// Note: requires additional types generated from: TeamDTO.proto
namespace Common.DTO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeagueDTO")]
  public partial class LeagueDTO : global::ProtoBuf.IExtensible
  {
    public LeagueDTO() {}
    
    private long _Id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _Region = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Region", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Region
    {
      get { return _Region; }
      set { _Region = value; }
    }
    private readonly global::System.Collections.Generic.List<Common.DTO.TeamDTO> _teams = new global::System.Collections.Generic.List<Common.DTO.TeamDTO>();
    [global::ProtoBuf.ProtoMember(4, Name=@"teams", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.DTO.TeamDTO> teams
    {
      get { return _teams; }
    }
  
    private string _Description = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _Logo = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Logo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Logo
    {
      get { return _Logo; }
      set { _Logo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}