//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MatchDTO.proto
// Note: requires additional types generated from: FieldDTO.proto
// Note: requires additional types generated from: TeamDTO.proto
namespace Common.DTO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchDTO")]
  public partial class MatchDTO : global::ProtoBuf.IExtensible
  {
    public MatchDTO() {}
    
    private long _Id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Date = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Date
    {
      get { return _Date; }
      set { _Date = value; }
    }
    private Common.DTO.FieldDTO _Field = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Common.DTO.FieldDTO Field
    {
      get { return _Field; }
      set { _Field = value; }
    }
    private string _Details = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"Details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Details
    {
      get { return _Details; }
      set { _Details = value; }
    }
    private Common.DTO.TeamDTO _Team1 = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Team1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Common.DTO.TeamDTO Team1
    {
      get { return _Team1; }
      set { _Team1 = value; }
    }
    private long _ScoreTeam1 = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ScoreTeam1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreTeam1
    {
      get { return _ScoreTeam1; }
      set { _ScoreTeam1 = value; }
    }
    private long _ScoreExtraTimeTeam1 = default(long);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ScoreExtraTimeTeam1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreExtraTimeTeam1
    {
      get { return _ScoreExtraTimeTeam1; }
      set { _ScoreExtraTimeTeam1 = value; }
    }
    private Common.DTO.TeamDTO _Team2 = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Team2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Common.DTO.TeamDTO Team2
    {
      get { return _Team2; }
      set { _Team2 = value; }
    }
    private long _ScoreTeam2 = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ScoreTeam2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreTeam2
    {
      get { return _ScoreTeam2; }
      set { _ScoreTeam2 = value; }
    }
    private long _ScoreExtraTimeTeam2 = default(long);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"ScoreExtraTimeTeam2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreExtraTimeTeam2
    {
      get { return _ScoreExtraTimeTeam2; }
      set { _ScoreExtraTimeTeam2 = value; }
    }
    private bool _Finished = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Finished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Finished
    {
      get { return _Finished; }
      set { _Finished = value; }
    }
    private bool _Forfeit = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Forfeit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Forfeit
    {
      get { return _Forfeit; }
      set { _Forfeit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}