//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ScoreTableResultDTO.proto
// Note: requires additional types generated from: TeamDTO.proto
namespace Common.DTO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreTableResultDTO")]
  public partial class ScoreTableResultDTO : global::ProtoBuf.IExtensible
  {
    public ScoreTableResultDTO() {}
    
    private Common.DTO.TeamDTO _Team = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Team", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Common.DTO.TeamDTO Team
    {
      get { return _Team; }
      set { _Team = value; }
    }
    private long _GamesPlayed = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"GamesPlayed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long GamesPlayed
    {
      get { return _GamesPlayed; }
      set { _GamesPlayed = value; }
    }
    private long _GamesWined = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"GamesWined", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long GamesWined
    {
      get { return _GamesWined; }
      set { _GamesWined = value; }
    }
    private long _GamesDrawn = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GamesDrawn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long GamesDrawn
    {
      get { return _GamesDrawn; }
      set { _GamesDrawn = value; }
    }
    private long _GamesLost = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GamesLost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long GamesLost
    {
      get { return _GamesLost; }
      set { _GamesLost = value; }
    }
    private long _ScoreFavor = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ScoreFavor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreFavor
    {
      get { return _ScoreFavor; }
      set { _ScoreFavor = value; }
    }
    private long _ScoreAgainst = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ScoreAgainst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreAgainst
    {
      get { return _ScoreAgainst; }
      set { _ScoreAgainst = value; }
    }
    private long _ScoreDifference = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ScoreDifference", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ScoreDifference
    {
      get { return _ScoreDifference; }
      set { _ScoreDifference = value; }
    }
    private long _Points = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Points
    {
      get { return _Points; }
      set { _Points = value; }
    }
    private long _Position = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private string _League = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"League", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string League
    {
      get { return _League; }
      set { _League = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}