//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TeamListDTO.proto
// Note: requires additional types generated from: TeamDTO.proto
namespace Common.DTO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamListDTO")]
  public partial class TeamListDTO : global::ProtoBuf.IExtensible
  {
    public TeamListDTO() {}
    
    private readonly global::System.Collections.Generic.List<Common.DTO.TeamDTO> _items = new global::System.Collections.Generic.List<Common.DTO.TeamDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.DTO.TeamDTO> items
    {
      get { return _items; }
    }
  
    private int _PageNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PageNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PageNumber
    {
      get { return _PageNumber; }
      set { _PageNumber = value; }
    }
    private int _PageTotal;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PageTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PageTotal
    {
      get { return _PageTotal; }
      set { _PageTotal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}