//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WeekDTO.proto
// Note: requires additional types generated from: MatchDTO.proto
namespace Common.DTO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeekDTO")]
  public partial class WeekDTO : global::ProtoBuf.IExtensible
  {
    public WeekDTO() {}
    
    private long _Id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private long _Season = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Season", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Season
    {
      get { return _Season; }
      set { _Season = value; }
    }
    private string _Title = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private string _Description = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _DateFrom = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"DateFrom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DateFrom
    {
      get { return _DateFrom; }
      set { _DateFrom = value; }
    }
    private string _DateTo = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"DateTo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DateTo
    {
      get { return _DateTo; }
      set { _DateTo = value; }
    }
    private readonly global::System.Collections.Generic.List<Common.DTO.MatchDTO> _matches = new global::System.Collections.Generic.List<Common.DTO.MatchDTO>();
    [global::ProtoBuf.ProtoMember(7, Name=@"matches", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.DTO.MatchDTO> matches
    {
      get { return _matches; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}